name: portal_flutter
description: Portal mobile client — замена Kivy (Android + iOS, один код).
publish_to: "none"
version: 1.0.6+7

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3
  path: ^1.9.0
  path_provider: ^2.1.4
  file_picker: ^8.0.3
  permission_handler: ^11.3.1
  flutter_background_service: ^5.0.10
  receive_sharing_intent: ^1.8.0
  intl: ^0.19.0
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
